apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-assignment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-assignment
  template:
    metadata:
      labels:
        app: k8-assignment
    spec:
      containers:
      - name: k8-container1
        image: judithkurian/k8-container1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: k8-assignment-service
spec:
  type: NodePort
  selector: 
    app: k8-assignment
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31200
