apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-assignment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-assignment
  template:
    metadata:
      labels:
        app: k8-assignment
    spec:
      containers:
      - name: k8-container1
        image: judithkurian/k8-container1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      volumeMounts:
        - name: data-volume
          mountPath: /judith_PV_dir
      volumes: 
        - name: data-volume
          persistentVolumeClaim:
            claimName: host-pvc

---

# service 1 for container 1

apiVersion: v1
kind: Service
metadata:
  name: k8-assignment-container1-service
spec:
  selector: 
    app: k8-assignment
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---

# service 2 for container 2

apiVersion: v1
kind: Service
metadata:
  name: k8-assignment-container2-service
spec:
  selector: 
    app: k8-assignment-container2
  ports: 
  - protocol: TCP
    port: 8081
    targetPort: 8081

---

#persistent volume for the containers

apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 10Gi
  storageClassName: standard
  accessModes: 
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: k8-assignment-disk
    fsType: ex14

---

# persistent volume claim for host-pv

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  access-modes:
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 10Gi
  storageClassName: standard
  selector:
    matchLabels: 
      name: host-pv